name: bench

on:
  schedule:
    - cron: 0 12 * * *
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bench:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install bombardier
        run: go install github.com/codesenberg/bombardier@latest

      - name: Install Dependencies
        run: npm ci

      - name: Run Benchmark
        run: deno run -A bench.js

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub"
          git config --global user.email "noreply@github.com"
          git commit -am "refactor: update benchmark"
          git push
